import Head from "next/head";

// HOOK
import { useState } from "react";

// ICONS
import { BiSearch } from "react-icons/bi";

export default function Home({ defaultData }) {
  const [locationData, setLocationData] = useState(defaultData);
  const [city, setCity] = useState("");
  const [notFound, setNotFound] = useState(false);
  const [weather, setWeather] = useState(
    `/img/${defaultData?.current.is_day ? "day" : "night"}/clear.avif`
  );

  const search = async (e) => {
    e.preventDefault();

    const API_KEY = "afcf51e89eaa450ba18115940221706";
    const res = await fetch(
      `http://api.weatherapi.com/v1/current.json?key=${API_KEY}&q=${city}&aqi=no`
    );
    const data = await res.json();

    // if searched city is not aviable set default data
    if (res.status !== 200) {
      setNotFound(true);

      return;
    }

    // Checking day/night and changing bg
    if (!data.current.is_day) {
      checkTime("night", data);
    } else {
      checkTime("day", data);
    }

    setLocationData(data);
    setNotFound(false);
    setCity("");
  };

  const checkTime = (time, data) => {
    if (data?.current.condition.code === 1000) {
      setWeather(`/img/${time}/clear.avif`);
    } else if (
      data?.current.condition.code === 1000 ||
      data?.current.condition.code === 1003 ||
      data?.current.condition.code === 1009 ||
      data?.current.condition.code === 1030 ||
      data?.current.condition.code === 1069 ||
      data?.current.condition.code === 1087 ||
      data?.current.condition.code === 1135 ||
      data?.current.condition.code === 1273 ||
      data?.current.condition.code === 1276 ||
      data?.current.condition.code === 1279 ||
      data?.current.condition.code === 1282
    ) {
      setWeather(`/img/${time}/cloudy.avif`);
    } else if (
      data?.current.condition.code === 1063 ||
      data?.current.condition.code === 1069 ||
      data?.current.condition.code === 1072 ||
      data?.current.condition.code === 1150 ||
      data?.current.condition.code === 1153 ||
      data?.current.condition.code === 1180 ||
      data?.current.condition.code === 1183 ||
      data?.current.condition.code === 1186 ||
      data?.current.condition.code === 1189 ||
      data?.current.condition.code === 1192 ||
      data?.current.condition.code === 1195 ||
      data?.current.condition.code === 1204 ||
      data?.current.condition.code === 1207 ||
      data?.current.condition.code === 1240 ||
      data?.current.condition.code === 1243 ||
      data?.current.condition.code === 1246 ||
      data?.current.condition.code === 1249 ||
      data?.current.condition.code === 1252
    ) {
      setWeather(`/img/${time}/rain.avif`);
    } else {
      setWeather(`/img/${time}/snow.avif`);
    }
  };

  const suggestedCities = async (city) => {
    const API_KEY = "afcf51e89eaa450ba18115940221706";
    const res = await fetch(
      `http://api.weatherapi.com/v1/current.json?key=${API_KEY}&q=${city}&aqi=no`
    );
    const data = await res.json();
    if (!data.current.is_day) {
      checkTime("night", data);
    } else {
      checkTime("day", data);
    }
    setLocationData(data);
  };

  return (
    <div className="">
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/116.png" />
      </Head>

      <main>
        <img className="main-bg-img" src={weather} alt="" />
        <div className="main__left">
          <h2 className="main__left-logo">the weather</h2>
          <div className="weather-info-box">
            <h2 className="weather-info-temp">
              {Math.floor(locationData?.current.temp_c)}&deg;
            </h2>
            <div className="weather-info-location">
              <p>
                {locationData?.location.name}, {locationData?.location.country}
              </p>
              <small> {locationData?.location.localtime}</small>
            </div>
            <div className="weather-info-about">
              <img
                src={locationData?.current.condition.icon}
                alt=""
                objectFit="contain"
              />
              <small>{locationData?.current.condition.text}</small>
            </div>
          </div>
        </div>

        <aside>
          <form className="aside-form" onSubmit={search}>
            <div>
              <input
                type="text"
                value={city}
                onChange={(e) => setCity(e.target.value)}
                placeholder="Search Location..."
              />
              {notFound && <p>Not Found</p>}
            </div>

            <button
              type="submit"
              className={`aside-form-btn ${
                locationData?.current.is_day ? "day" : "night"
              }`}
            >
              <BiSearch />
            </button>
          </form>

          <div className="aside-bookmark">
            <p onClick={() => suggestedCities("Tashkent")}>Tashkent</p>
            <p onClick={() => suggestedCities("Qarshi")}>Qarshi</p>
            <p onClick={() => suggestedCities("Moscow")}> Moscow</p>
            <p onClick={() => suggestedCities("New York")}>New York</p>
            <p onClick={() => suggestedCities("Tokyo")}>Tokyo</p>
          </div>

          <div className="aside-weather-details">
            <h3>Weather Details</h3>

            <p>
              <span>Cloudy:</span> {locationData?.current.cloud}%
            </p>
            <p>
              <span>Humidty:</span> {locationData?.current.humidity}%
            </p>
            <p>
              <span>Wind:</span> {locationData?.current.gust_kph}km/h
            </p>
          </div>
        </aside>
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const res = await fetch(
    `http://api.weatherapi.com/v1/current.json?key=${process.env.WEATHER_API_KEY}&q=Tashkent&aqi=no`
  );

  const data = await res.json();

  return {
    props: {
      defaultData: data,
    },
  };
}
